[build]
  command = "sudo apt-get update && sudo apt-get install -y stagit && mkdir -p stagit && cd stagit && stagit -l 100 .. && cd .. && npm run production"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.10.0"
